#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = 'kitty'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#FD971F'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = "nix-shell"
    style = "plain"
    foreground = "white"  
    template = "{{if ne .Type \"unknown\"}} <#5178C4>n</><#5F8FCF>i</><#6DA5DA>x</><#7BBBE4>:(</>shell<#7FBBE5>)</>{{end}}"

  [[blocks.segments]]
    type = "docker"
    style = "plain"
    foreground = "lightBlue"
    template = " context:(<white>{{ .Context }}</>)"
    
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#F1502F'
    template = ' git:(<white>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>)</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
  

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    template = '{{ .FormattedMs }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "#FD971F",
    ]
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "#FD971F",
  ]
  template = '❯ '

[secondary_prompt]
  foreground = '#FD971F'
  template = '❯❯ '